[package]
name = "cce-preview"
version = "0.1.0"
edition = "2021"

[dependencies]
cce-ui = { git = "https://git.lucas.co/cce-ui.git", rev = "e933422c4efd8066f8fe1596348d9e14ae6f227e" }
calloop = "0.13.0"
wayland-client = { version = "0.31", features = ["system"] }
image = { version = "0.25", default-features = false, features = [
    "png", "jpeg", "gif", "webp", "bmp", "tiff", "ico",
] }
log = "0.4"
env_logger = "0.11"
