[package]
name = "cce-preview"
version = "0.1.0"
edition = "2021"

[dependencies]
cce-ui = { git = "https://github.com/lsgalante/cce-ui.git", rev = "ff4b28942d78995587c3ab50bd7fd7ad4efe04d7" }
calloop = "0.13.0"
wayland-client = { version = "0.31", features = ["system"] }
image = { version = "0.25", default-features = false, features = [
    "png", "jpeg", "gif", "webp", "bmp", "tiff", "ico",
] }
log = "0.4"
env_logger = "0.11"
