[package]
name = "cce-preview"
version = "0.1.0"
edition = "2021"

[dependencies]
cce-ui = { git = "https://github.com/lsgalante/cce-ui.git", rev = "d72a3b97e05498e0016ac7839a854ef3ba7b8d22" }
calloop = "0.13.0"
wayland-client = { version = "0.31", features = ["system"] }
image = { version = "0.25", default-features = false, features = [
    "png", "jpeg", "gif", "webp", "bmp", "tiff", "ico",
] }
log = "0.4"
env_logger = "0.11"
